base_model: /data/outputs/shisa-v2.1c-lfm2-350m-sft

load_in_8bit: false
load_in_4bit: false
strict: false

# Disable device_map for multi-GPU training
device_map: null

eot_tokens:
  - "<|im_end|>"
chat_template: tokenizer_default
rl: dpo
datasets:
  - path: chotto-20251010.dpo.jsonl
    type: chat_template.argilla_chat
    field_chosen: chosen
    field_rejected: rejected
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
    roles_to_train: ["assistant"]

dataset_prepared_path:
val_set_size: 0
output_dir: /data/outputs/shisa-v2.1c-lfm2-350m-dpo

sequence_len: 4096
sample_packing: false
flash_attention: true
pad_to_sequence_len: false

neftune_noise_alpha: 5

use_wandb: true
wandb_entity: augmxnt
wandb_project: liquid-hackathon-tokyo
wandb_name: "8xMI300 shisa-v2.1c-lfm2-350m-dpo"

# GBS=128 / 8 GPU / MBS=16
gradient_accumulation_steps: 1
micro_batch_size: 16
num_epochs: 1
optimizer: adamw_torch_8bit
lr_scheduler: constant_with_warmup
learning_rate: 3e-6 # 5.98e-07 @ GBS=64

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1

warmup_ratio: 0.03
saves_per_epoch: 2
save_total_limit: 2

deepspeed: zero3_bf16.json
weight_decay: 1e-4
fsdp:
fsdp_config:
special_tokens:
